services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s
      POSTGRES_DB: sports_betting
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: s
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:s@db:5432/sports_betting
    command: ["sh", "-c", "python infra/db/wait_for_postgres.py && python infra/db/init_db.py"]
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  pgdata:
  pgadmin-data: