"""change to recent obs

Revision ID: 023ec92bda41
Revises: 693b23239064
Create Date: 2025-09-20 19:22:53.782701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023ec92bda41'
down_revision: Union[str, Sequence[str], None] = '693b23239064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineup_entries', sa.Column('recent_ops', sa.Float(), nullable=True))
    op.drop_column('lineup_entries', 'recent_avg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineup_entries', sa.Column('recent_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('lineup_entries', 'recent_ops')
    # ### end Alembic commands ###
