"""add total win/loss to feature_tables

Revision ID: 22a92c9f1126
Revises: 2955a256b8f4
Create Date: 2025-09-18 01:39:44.231245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a92c9f1126'
down_revision: Union[str, Sequence[str], None] = '2955a256b8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_features', sa.Column('wins_season', sa.Integer(), nullable=True))
    op.add_column('team_features', sa.Column('losses_season', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_features', 'losses_season')
    op.drop_column('team_features', 'wins_season')
    # ### end Alembic commands ###
