"""add new columns

Revision ID: 2caba8a9784a
Revises: 75debe2d7d09
Create Date: 2025-07-12 17:00:36.706698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2caba8a9784a'
down_revision: Union[str, Sequence[str], None] = '75debe2d7d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_game_stats', sa.Column('walks_batting', sa.Integer(), nullable=True))
    op.add_column('player_game_stats', sa.Column('doubles', sa.Integer(), nullable=True))
    op.add_column('player_game_stats', sa.Column('triples', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('throwing_hand', sa.String(), nullable=True))
    op.alter_column('weather', 'wind_direction',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather', 'wind_direction',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('players', 'throwing_hand')
    op.drop_column('player_game_stats', 'triples')
    op.drop_column('player_game_stats', 'doubles')
    op.drop_column('player_game_stats', 'walks_batting')
    # ### end Alembic commands ###
