"""add over_price

Revision ID: 575a5766d4d1
Revises: c8d569432577
Create Date: 2025-07-10 22:28:38.371214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575a5766d4d1'
down_revision: Union[str, Sequence[str], None] = 'c8d569432577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('over_price', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('under_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'under_price')
    op.drop_column('games', 'over_price')
    # ### end Alembic commands ###
