"""add outs pitched

Revision ID: 5d5eef3964a1
Revises: 22a92c9f1126
Create Date: 2025-09-19 00:52:07.813334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5eef3964a1'
down_revision: Union[str, Sequence[str], None] = '22a92c9f1126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_game_stats', sa.Column('outs_pitched', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_game_stats', 'outs_pitched')
    # ### end Alembic commands ###
