"""add lineups

Revision ID: 693b23239064
Revises: 5d5eef3964a1
Create Date: 2025-09-20 19:11:32.449660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693b23239064'
down_revision: Union[str, Sequence[str], None] = '5d5eef3964a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineup_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('batting_order', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('defensive_position', sa.String(length=3), nullable=True),
    sa.Column('avg_season', sa.Float(), nullable=True),
    sa.Column('obp_season', sa.Float(), nullable=True),
    sa.Column('slg_season', sa.Float(), nullable=True),
    sa.Column('ops_season', sa.Float(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('rbis', sa.Integer(), nullable=True),
    sa.Column('recent_avg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'batting_order', name='uq_lineup_slot')
    )
    op.drop_table('bets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sportsbook', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bet_side', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bet_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('edge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bet_outcome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('bets_game_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bets_pkey'))
    )
    op.drop_table('lineup_entries')
    # ### end Alembic commands ###
