"""add moneyline cols

Revision ID: 72c1326588bf
Revises: a06e6d8fa2bc
Create Date: 2025-09-07 23:39:32.540323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c1326588bf'
down_revision: Union[str, Sequence[str], None] = 'a06e6d8fa2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_ml_price', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('away_ml_price', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('market', sa.String(), nullable=True))
    op.execute("UPDATE predictions SET market = 'TOTAL' WHERE market IS NULL")
    op.alter_column("predictions", "market", nullable=False)
    op.add_column('predictions', sa.Column('home_win_prob', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('away_win_prob', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'away_win_prob')
    op.drop_column('predictions', 'home_win_prob')
    op.drop_column('predictions', 'market')
    op.drop_column('games', 'away_ml_price')
    op.drop_column('games', 'home_ml_price')
    # ### end Alembic commands ###
