"""add probably pitchers

Revision ID: b1a647607e16
Revises: 575a5766d4d1
Create Date: 2025-07-11 21:23:16.974725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a647607e16'
down_revision: Union[str, Sequence[str], None] = '575a5766d4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_probable_pitcher_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_probable_pitcher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'players', ['away_probable_pitcher_id'], ['id'])
    op.create_foreign_key(None, 'games', 'players', ['home_probable_pitcher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'away_probable_pitcher_id')
    op.drop_column('games', 'home_probable_pitcher_id')
    # ### end Alembic commands ###
