"""add_player_season_stats

Revision ID: c3c9332facc5
Revises: 6400d8e6b6ea
Create Date: 2026-02-22 01:03:58.558539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c9332facc5'
down_revision: Union[str, Sequence[str], None] = '6400d8e6b6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('at_bats', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('rbis', sa.Integer(), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('walks_batting', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('obp', sa.Float(), nullable=True),
    sa.Column('slg', sa.Float(), nullable=True),
    sa.Column('ops', sa.Float(), nullable=True),
    sa.Column('games_pitched', sa.Integer(), nullable=True),
    sa.Column('outs_pitched', sa.Integer(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('walks_pitched', sa.Integer(), nullable=True),
    sa.Column('hits_allowed', sa.Integer(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season_year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_season_stats')
    # ### end Alembic commands ###
