"""add hr_total_runs_line

Revision ID: c8d569432577
Revises: f690a641f0bf
Create Date: 2025-07-10 22:09:27.371426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d569432577'
down_revision: Union[str, Sequence[str], None] = 'f690a641f0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('hr_total_runs_line', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'hr_total_runs_line')
    # ### end Alembic commands ###
